import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  product: {
    backgroundColor: '#343a4042',
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 16,
    borderRadius: 8,
  },
  title: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 4,
    fontWeight: 'bold',
  },
  imgContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
    borderRadius: 18,
    marginVertical: 20,
  },
  logo: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    borderRadius: 18,
    marginBottom: 5,
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  header: {
    color: '#343a4042',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: 15,
  },
  relatedContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
  },
  logoText: {
    color: '#ff9900',
    fontSize: 16,
    fontWeight: 'bold',
  },
  catContainer: {
    marginBottom: 15,
    marginTop: 40,
    gap: 5,
    flexDirection: 'row',
  },
  catBtn: {
    backgroundColor: '#ff9900',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginTop: 8,
    padding: 5,
  },
  catBtnText: {
    color: '#f8f9fa',
    fontSize: 13,
    fontWeight: 'bold',
  },
  btn: {
    backgroundColor: '#ff9900',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginTop: 8,
    padding: 9,
    marginHorizontal: 50,
  },
  btnPL: {
    backgroundColor: '#ff9900',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginTop: 8,
    padding: 9,
    marginHorizontal: 90,
  },
  removeBtn: {
    backgroundColor: '#343a40cf',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginTop: 8,
    padding: 9,
    marginHorizontal: 40,
  },
  deleteBtn: {
    backgroundColor: '#343a40cf',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginTop: 8,
    padding: 9,
    marginHorizontal: 80,
  },
  miniBtn: {
    backgroundColor: '#ff9900',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    marginTop: 8,
    marginBottom: 8,
    padding: 12,
    width: 50,
  },
  btnText: {
    color: '#f8f9fa',
    fontSize: 16,
    fontWeight: 'bold',
  },
  miniBtnText: {
    color: '#f8f9fa',
    fontSize: 20,
    fontWeight: 'bold',
  },
  btnPlText: {
    color: '#f8f9fa',
    fontSize: 16,
    fontWeight: 'bold',
  },
  price: {
    fontSize: 16,
    color: '#fff',
    marginVertical: 7,
  },
});
export default styles;
